const content=[{title:"5 Kesalahan Payroll yang Sering Terjadi",platform:"Instagram",pillar:"Payroll Education",reach:42300,eng:5414,leads:28,score:94},{title:"THR Calculator 2026",platform:"TikTok",pillar:"Lead Magnet",reach:61800,eng:7045,leads:35,score:96},{title:"HR Admin vs HR Tech",platform:"LinkedIn",pillar:"Problem / Solution",reach:18900,eng:1833,leads:21,score:88},{title:"Payroll Checklist Sebelum Payday",platform:"Instagram",pillar:"Payroll Education",reach:26700,eng:2376,leads:17,score:81},{title:"7 Fitur Payroll Wajib",platform:"Instagram",pillar:"Product Education",reach:26700,eng:1496,leads:12,score:71},{title:"POV: HR Menghitung 300 Gaji Manual",platform:"TikTok",pillar:"Relatable HR",reach:15400,eng:770,leads:5,score:58},{title:"Free Demo Payroll Software",platform:"Instagram",pillar:"Promotional",reach:11200,eng:291,leads:4,score:41}];
const leads=[{company:"PT Nusantara Digital",source:"THR Calculator",employees:250,intent:"High",score:92,stage:"Demo",next:"Contact sales"},{company:"CV Maju Bersama",source:"Payroll Tips",employees:85,intent:"High",score:86,stage:"Qualified",next:"WhatsApp"},{company:"PT Arunika Tech",source:"LinkedIn",employees:140,intent:"Medium",score:71,stage:"Nurture",next:"Email sequence"},{company:"Studio Kreatif",source:"Instagram",employees:35,intent:"Warm",score:54,stage:"New",next:"Educational content"},{company:"PT Sentra Logistik",source:"Calculator",employees:420,intent:"High",score:89,stage:"Demo",next:"Sales call"}];
const calendar=[["29 Sep","Instagram","5 Kesalahan Payroll","Education","Checklist","Ready"],["30 Sep","TikTok","POV HR Payday","Relatable HR","Calculator","Draft"],["02 Okt","LinkedIn","Excel vs Payroll Tech","Product Education","Demo","Scheduled"],["05 Okt","Instagram","Cara Hitung Lembur","Payroll Education","Template","Planned"],["07 Okt","TikTok","Payroll Cost Calculator","Lead Magnet","Calculator","Planned"]];
let recs=[["HIGH OPPORTUNITY · 94/100","Berapa biaya payroll perusahaanmu jika masih manual?","Short video 30–45 detik. Pillar: Problem/Solution. CTA: Payroll Cost Calculator. Target: HR Manager & Business Owner."],["HIGH OPPORTUNITY · 91/100","5 Kesalahan Menghitung Lembur yang Sering Terjadi","Carousel. Pillar: Payroll Education. CTA: Download Payroll Checklist. Target: HR Admin."],["HIGH OPPORTUNITY · 88/100","Excel vs Payroll Software: Kapan Harus Pindah?","LinkedIn document. Pillar: Product Education. CTA: Free Demo. Target: SME Owner."],["TEST IDEA · 82/100","POV: Tanggal 25 dan kamu masih menghitung gaji 300 karyawan","TikTok/Reels. Pillar: Relatable HR. CTA: See how it works. Target: HR & Finance."]];
let charts={};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function renderContent(){const q=($("#contentSearch")?.value||"").toLowerCase(),p=$("#contentPlatform")?.value||"all";$("#contentRows").innerHTML=content.filter(x=>(p==="all"||x.platform===p)&&x.title.toLowerCase().includes(q)).map(x=>{const er=(x.eng/x.reach*100).toFixed(1);return "<tr><td><b>"+x.title+"</b></td><td>"+x.platform+"</td><td>"+x.pillar+"</td><td>"+x.reach.toLocaleString()+"</td><td>"+er+"%</td><td>"+x.leads+"</td><td><b>"+x.score+"</b></td><td><span class='tag "+(x.score>=85?"good":x.score>=60?"warn":"bad")+"'>"+(x.score>=85?"Excellent":x.score>=60?"Average":"Low")+"</span></td></tr>"}).join("")}
function renderLeads(){$("#leadRows").innerHTML=leads.map(l=>"<tr><td><b>"+l.company+"</b></td><td>"+l.source+"</td><td>"+l.employees+"</td><td><span class='tag "+(l.intent==="High"?"good":l.intent==="Medium"?"warn":"bad")+"'>"+l.intent+"</span></td><td><b>"+l.score+"</b></td><td>"+l.stage+"</td><td><button class='btn' onclick="toast('"+l.next+"')">"+l.next+"</button></td></tr>").join("")}
function renderCalendar(){$("#calendarRows").innerHTML=calendar.map(r=>"<tr>"+r.map((c,i)=>"<td>"+(i===5?"<span class='tag good'>"+c+"</span>":c)+"</td>").join("")+"</tr>").join("")}
function renderTop(){$("#topContent").innerHTML=[...content].sort((a,b)=>b.leads-a.leads).slice(0,4).map(x=>"<div class='item'><b>"+x.title+"</b><p>"+x.platform+" · "+x.leads+" qualified leads · score "+x.score+"</p></div>").join("")}
function renderSignals(){$("#signals").innerHTML="<div class='signal'><strong>🔥 Educational content is strongest</strong><span>Payroll Education has the best combined engagement + lead efficiency.</span></div><div class='signal'><strong>🎯 Lead magnets convert</strong><span>Calculator/checklist CTAs outperform generic demo promotion in this dataset.</span></div><div class='signal'><strong>📉 Promotion needs context</strong><span>Direct promotional posts show lower engagement and lead efficiency.</span></div>"}
function renderActions(){$("#actions").innerHTML="<div class='signal'><strong>1. Create 2 payroll tools</strong><span>THR calculator + payroll cost calculator.</span></div><div class='signal'><strong>2. Repurpose top topic</strong><span>Turn payroll mistakes into video, carousel and LinkedIn document.</span></div><div class='signal'><strong>3. Move hot leads</strong><span>Contact leads scoring above 85 within the sales workflow.</span></div>"}
function renderPillars(){if(charts.pillar)charts.pillar.destroy();charts.pillar=new Chart($("#pillarChart"),{type:"bar",data:{labels:["Payroll Edu","Problem/Solution","Lead Magnet","Product Edu","Relatable HR","Promotional"],datasets:[{data:[92,86,81,73,61,48],backgroundColor:"#635bff",borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:"y",plugins:{legend:{display:false}},scales:{x:{max:100,grid:{color:"#eef0f4"}},y:{grid:{display:false}}}}});$("#pillarInsights").innerHTML="<div class='item'><b>Payroll Education</b><p>Prioritize THR, overtime, attendance and payslip topics.</p></div><div class='item'><b>Lead Magnet</b><p>Turn calculators and templates into gated conversion assets.</p></div><div class='item'><b>Promotional</b><p>Use after educational context instead of as the main stream.</p></div>"}
function renderFunnel(){$("#funnelBox").innerHTML=[["Content Reach","248,500"],["Engagement","21,620"],["Website Visits","4,840"],["Leads","386"],["Qualified Leads","126"],["Demo","32"]].map((s,i)=>"<div class='fstep' style='width:"+(92-i*11)+"%'><b>"+s[0]+"</b><small>"+s[1]+"</small></div>").join("");$("#channelLead").innerHTML="<div class='item'><b>Instagram</b><p>44% of qualified leads in the sample.</p></div><div class='item'><b>TikTok</b><p>37% of qualified leads; lead magnets are strong.</p></div><div class='item'><b>LinkedIn</b><p>19% of qualified leads; useful for professional topics.</p></div>";$("#funnelInsights").innerHTML="<div class='item'><b>Biggest opportunity</b><p>Improve engagement → website visit with stronger CTA and landing pages.</p></div><div class='item'><b>Business KPI</b><p>Keep qualified leads and demo conversion alongside reach and ER.</p></div>"}
function renderRecs(){$("#recommendationGrid").innerHTML=recs.map(r=>"<article class='rec'><div class='eyebrow'>"+r[0]+"</div><h3>"+r[1]+"</h3><p>"+r[2]+"</p></article>").join("")}
function buildCharts(){charts.trend=new Chart($("#trendChart"),{type:"line",data:{labels:["01 Sep","05 Sep","10 Sep","15 Sep","20 Sep","25 Sep","29 Sep"],datasets:[{label:"Reach (K)",data:[24,31,28,42,36,49,38],borderColor:"#635bff",backgroundColor:"rgba(99,91,255,.08)",fill:true,tension:.4},{label:"Engagement %",data:[7,8,7.5,9.2,8.4,10.1,9.4],borderColor:"#149765",tension:.4,yAxisID:"y1"}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{labels:{font:{size:10}}}},scales:{x:{grid:{display:false}},y:{grid:{color:"#eef0f4"}},y1:{position:"right",grid:{drawOnChartArea:false}}}}});charts.mix=new Chart($("#mixChart"),{type:"doughnut",data:{labels:["Instagram","TikTok","LinkedIn"],datasets:[{data:[44,37,19],backgroundColor:["#635bff","#149765","#f59e0b"],borderWidth:0}]},options:{cutout:"68%",plugins:{legend:{position:"bottom",labels:{font:{size:10},boxWidth:10}}}}});$("#platformTabs").innerHTML=["All","Instagram","TikTok","LinkedIn"].map(x=>"<button class='btn' style='font-size:10px;padding:6px 8px;margin-left:4px'>"+x+"</button>").join("")}
function openModal(type){$("#modalBody").innerHTML=type==="lead"?"<h2>Add Lead</h2><p>Tambahkan lead ke dataset prototype.</p><div class='form'><input id='mCompany' placeholder='Nama perusahaan'><input id='mEmployees' type='number' placeholder='Jumlah karyawan'><select id='mIntent'><option>High</option><option>Medium</option><option>Warm</option></select><button class='btn primary' onclick='saveLead()'>Save lead</button></div>":"<h2>Schedule Content</h2><p>Rencanakan konten dari insight saat ini.</p><div class='form'><input id='mDate' type='date'><input id='mTopic' placeholder='Topik konten'><select id='mPlatform'><option>Instagram</option><option>TikTok</option><option>LinkedIn</option></select><button class='btn primary' onclick='saveSchedule()'>Add to calendar</button></div>";$("#modal").classList.add("show")}
function closeModal(){$("#modal").classList.remove("show")}
function saveLead(){const c=$("#mCompany").value||"New Company",e=Number($("#mEmployees").value||50),i=$("#mIntent").value,s=i==="High"?86:i==="Medium"?70:53;leads.unshift({company:c,source:"Manual",employees:e,intent:i,score:s,stage:"New",next:"Qualify"});renderLeads();closeModal();toast("Lead tersimpan")}
function saveSchedule(){const d=$("#mDate").value||"New",t=$("#mTopic").value||"New Topic",p=$("#mPlatform").value;calendar.unshift([d,p,t,"New Pillar","CTA","Planned"]);renderCalendar();closeModal();toast("Konten masuk kalender")}
function generateRecommendations(){recs.unshift(["NEW SIGNAL · 90/100","Buat seri Payroll Myth vs Fact","Short video + carousel. CTA: payroll checklist. Objective: increase saves, shares and lead capture."]);renderRecs();toast("Recommendation baru dibuat")}
function saveSettings(){localStorage.setItem("hrgrowBrand",$("#brandName").value);toast("Settings tersimpan")}
function downloadReport(){const rows=[["title","platform","pillar","reach","engagement","engagement_rate","leads","score"],...content.map(x=>[x.title,x.platform,x.pillar,x.reach,x.eng,(x.eng/x.reach*100).toFixed(2),x.leads,x.score])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="hrgrow-content-report.csv";a.click();URL.revokeObjectURL(a.href);toast("CSV report diunduh")}
const meta={overview:["Marketing Overview","Social media → intelligence → leads → business outcomes."],content:["Content Intelligence","Analyze each post and connect performance to lead outcomes."],pillars:["Content Pillar Intelligence","Compare themes, formats and CTA effectiveness."],leads:["Lead Intelligence","Lead scoring based on company profile, intent and marketing actions."],funnel:["Marketing Funnel","Measure the journey from content exposure to sales opportunity."],recommendations:["Recommendations","Decision support generated from the current dataset."],calendar:["Content Calendar","Plan future content around high-intent opportunities."],reports:["Reports","Generate a management-ready summary from the active dataset."],settings:["Settings","Workspace configuration for the prototype."]};
$$('#nav a').forEach(a=>a.onclick=()=>{const p=a.dataset.page;$$('#nav a').forEach(x=>x.classList.toggle("active",x===a));$$('.page').forEach(x=>x.classList.toggle("active",x.id===p));$("#pageTitle").textContent=meta[p][0];$("#pageSub").textContent=meta[p][1]});
$("#contentSearch").oninput=renderContent;$("#contentPlatform").onchange=renderContent;$("#addBtn").onclick=()=>openModal("calendar");renderContent();renderLeads();renderCalendar();renderTop();renderSignals();renderActions();renderPillars();renderFunnel();renderRecs();buildCharts();if(localStorage.getItem("hrgrowBrand"))$("#brandName").value=localStorage.getItem("hrgrowBrand");