const defaultProducts=[{id:1,name:"Kopi Susu Gula Aren",cat:"Coffee",price:22000,stock:42,emoji:"☕"},{id:2,name:"Americano",cat:"Coffee",price:18000,stock:35,emoji:"☕"},{id:3,name:"Cappuccino",cat:"Coffee",price:24000,stock:28,emoji:"☕"},{id:4,name:"Matcha Latte",cat:"Non-Coffee",price:26000,stock:21,emoji:"🍵"},{id:5,name:"Chocolate",cat:"Non-Coffee",price:24000,stock:19,emoji:"🍫"},{id:6,name:"Lychee Tea",cat:"Tea",price:18000,stock:31,emoji:"🧋"},{id:7,name:"French Fries",cat:"Food",price:20000,stock:16,emoji:"🍟"},{id:8,name:"Chicken Rice Bowl",cat:"Food",price:32000,stock:12,emoji:"🍚"},{id:9,name:"Croissant",cat:"Pastry",price:22000,stock:9,emoji:"🥐"}];
let products=JSON.parse(localStorage.getItem("cafe_products")||"null")||defaultProducts,cart=[],orders=JSON.parse(localStorage.getItem("cafe_orders")||"[]"),settings=JSON.parse(localStorage.getItem("cafe_settings")||"null")||{name:"Kopi Senja Cafe",address:"Surabaya, Jawa Timur",footer:"Terima kasih sudah berkunjung!",logo:""},activeCat="All",editingId=null,lastOrder=null;
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);const saveProducts=()=>localStorage.setItem("cafe_products",JSON.stringify(products));const saveSettings=()=>localStorage.setItem("cafe_settings",JSON.stringify(settings));function toast(s){const e=document.getElementById("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function renderCats(){const cats=["All",...new Set(products.map(p=>p.cat))];categories.innerHTML=cats.map(c=>'<button class="'+(c===activeCat?"active":"")+'" onclick="setCat(\''+c.replace(/'/g,"\\'")+'\')">'+c+"</button>").join("")}function setCat(c){activeCat=c;renderCats();renderProducts()}
function renderProducts(){document.getElementById("products").innerHTML=products.filter(p=>activeCat==="All"||p.cat===activeCat).map(p=>'<button class="product" onclick="add('+p.id+')"><span class="emoji">'+p.emoji+'</span><h3>'+p.name+'</h3><div class="price">'+money(p.price)+'</div><div class="stock">Stok: '+p.stock+'</div></button>').join("")||'<div class="panel">Belum ada produk.</div>'}
function add(id){const p=products.find(x=>x.id===id);if(!p||p.stock<=0)return toast("Stok produk habis.");const x=cart.find(x=>x.id===id);if(x){if(x.qty>=p.stock)return toast("Quantity melebihi stok.");x.qty++}else cart.push({...p,qty:1});renderCart()}
function change(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);renderCart()}
function renderCart(){cartItems.innerHTML=cart.length?cart.map(x=>'<div class="cart-row"><div><b>'+x.name+'</b><br><small>'+money(x.price)+' × '+x.qty+'</small></div><div class="qty"><button onclick="change('+x.id+',-1)">−</button><b>'+x.qty+'</b><button onclick="change('+x.id+',1)">+</button></div></div>').join(""):'<p style="padding:50px 0;text-align:center">Belum ada item.</p>';const sub=cart.reduce((s,x)=>s+x.price*x.qty,0),tax=sub*.1;subtotal.textContent=money(sub);discount.textContent=money(0);document.getElementById("tax").textContent=money(tax);total.textContent=money(sub+tax)}
function completeCheckout(){if(!cart.length)return toast("Tambahkan produk dulu.");const sub=cart.reduce((s,x)=>s+x.price*x.qty,0),tax=sub*.1,o={id:"ORD-"+Date.now().toString().slice(-6),items:cart.map(x=>({name:x.name,qty:x.qty,price:x.price})),total:sub+tax,payment:payment.value,note:note.value,status:"Selesai",time:new Date().toLocaleString("id-ID")};orders.unshift(o);localStorage.setItem("cafe_orders",JSON.stringify(orders));o.items.forEach(i=>{const p=products.find(x=>x.name===i.name);if(p)p.stock=Math.max(0,p.stock-i.qty)});saveProducts();lastOrder=o;renderAll();showReceipt(o)}
function receiptHTML(o){return '<div class="receipt-brand">'+(settings.logo?'<img src="'+settings.logo+'" alt="Logo">':'<div class="receipt-logo">LOGO</div>')+'<h2>'+settings.name+'</h2><p>'+settings.address+'</p></div><hr><div>No: '+o.id+'<br>'+o.time+'<br>Bayar: '+o.payment+'</div><hr>'+o.items.map(i=>'<div class="receipt-line"><span>'+i.name+'<br>'+i.qty+' × '+money(i.price)+'</span><b>'+money(i.qty*i.price)+'</b></div>').join("")+'<hr><div class="receipt-line"><b>TOTAL</b><b>'+money(o.total)+'</b></div>'+(o.note?'<p><b>Catatan:</b> '+o.note+'</p>':'')+'<hr><center>'+settings.footer+'</center>'}
function showReceipt(o){receiptPreview.innerHTML=receiptHTML(o);receiptModal.classList.remove("hidden")}
function printReceipt(){const w=window.open("","_blank","width=420,height=700");if(!w)return toast("Izinkan popup browser untuk mencetak.");w.document.write('<html><head><title>Struk '+lastOrder.id+'</title><style>body{font-family:Arial,sans-serif;width:320px;margin:20px auto;font-size:12px}.receipt-brand{text-align:center}.receipt-brand img{max-width:100px;max-height:70px}.receipt-logo{width:70px;height:50px;margin:auto;border:1px dashed #999;display:grid;place-items:center}.receipt-line{display:flex;justify-content:space-between;margin:8px 0}hr{border:0;border-top:1px dashed #999;margin:12px 0}</style></head><body>'+receiptHTML(lastOrder)+'<script>window.print();<\\/script></body></html>');w.document.close()}
function renderAdmin(){productAdmin.innerHTML='<table><thead><tr><th>Produk</th><th>Kategori</th><th>Harga</th><th>Stok</th><th>Aksi</th></tr></thead><tbody>'+products.map(p=>'<tr><td>'+p.emoji+' <b>'+p.name+'</b></td><td>'+p.cat+'</td><td>'+money(p.price)+'</td><td>'+p.stock+'</td><td><button class="table-btn" onclick="editProduct('+p.id+')">Edit</button> <button class="table-btn danger" onclick="deleteProduct('+p.id+')">Hapus</button></td></tr>').join("")+'</tbody></table>'}
function openProduct(id=null){editingId=id;productModalTitle.textContent=id?"Edit Produk":"Tambah Produk";const p=products.find(x=>x.id===id);pName.value=p?.name||"";pPrice.value=p?.price||"";pCat.value=p?.cat||"Coffee";pStock.value=p?.stock??0;pEmoji.value=p?.emoji||"☕";productModal.classList.remove("hidden")}
function editProduct(id){openProduct(id)}function deleteProduct(id){const p=products.find(x=>x.id===id);if(!p)return;if(!confirm("Hapus produk "+p.name+"?"))return;products=products.filter(x=>x.id!==id);saveProducts();renderAll();toast("Produk dihapus.")}
function saveProduct(){const data={id:editingId||Date.now(),name:pName.value.trim(),price:Number(pPrice.value),cat:pCat.value.trim()||"Lainnya",stock:Number(pStock.value),emoji:pEmoji.value.trim()||"🍽️"};if(!data.name||!data.price)return toast("Nama dan harga wajib diisi.");if(editingId)products=products.map(p=>p.id===editingId?data:p);else products.push(data);saveProducts();productModal.classList.add("hidden");renderAll();toast(editingId?"Produk diperbarui.":"Produk ditambahkan.")}
function renderOrders(){orderList.innerHTML='<table><thead><tr><th>Order</th><th>Waktu</th><th>Item</th><th>Pembayaran</th><th>Total</th><th>Status</th></tr></thead><tbody>'+(orders.map(o=>'<tr><td><b>'+o.id+'</b></td><td>'+o.time+'</td><td>'+o.items.reduce((s,i)=>s+i.qty,0)+' item</td><td>'+o.payment+'</td><td><b>'+money(o.total)+'</b></td><td><span class="status">'+o.status+'</span></td></tr>').join("")||'<tr><td colspan="6">Belum ada pesanan.</td></tr>')+'</tbody></table>'}
function renderInventory(){inventoryList.innerHTML='<table><thead><tr><th>Produk</th><th>Kategori</th><th>Stok</th><th>Status</th></tr></thead><tbody>'+products.map(p=>'<tr><td><b>'+p.name+'</b></td><td>'+p.cat+'</td><td>'+p.stock+'</td><td class="'+(p.stock<10?"low":"")+'">'+(p.stock<10?"Segera restock":"Aman")+'</td></tr>').join("")+'</tbody></table>'}
function renderReports(){const revenue=orders.reduce((s,o)=>s+o.total,0),items=orders.reduce((s,o)=>s+o.items.reduce((a,i)=>a+i.qty,0),0),avg=orders.length?revenue/orders.length:0;const counts={};orders.forEach(o=>o.items.forEach(i=>counts[i.name]=(counts[i.name]||0)+i.qty));const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);reportCards.innerHTML=[["Omzet",money(revenue)],["Transaksi",orders.length],["Item terjual",items],["Rata-rata order",money(avg)]].map(x=>'<div class="metric"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join("");topProducts.innerHTML="<h3>Produk Terlaris</h3>"+(top.map((x,i)=>'<p style="padding:9px 0;border-bottom:1px solid #eee">'+(i+1)+". "+x[0]+' <b style="float:right">'+x[1]+' terjual</b></p>').join("")||"<p>Belum ada data.</p>")}
function renderSettings(){storeName.value=settings.name;storeAddress.value=settings.address;receiptFooter.value=settings.footer;logoPreview.innerHTML=settings.logo?'<img src="'+settings.logo+'">':"LOGO"}
function renderAll(){renderCats();renderProducts();renderAdmin();renderOrders();renderInventory();renderReports();renderSettings();renderCart()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.view).classList.add("active")});
clearCart.onclick=()=>{cart=[];renderCart()};checkout.onclick=completeCheckout;addProduct.onclick=()=>openProduct();closeProduct.onclick=()=>productModal.classList.add("hidden");saveProduct.onclick=saveProduct;closeReceipt.onclick=()=>receiptModal.classList.add("hidden");printReceipt.onclick=printReceipt;newOrder.onclick=()=>{receiptModal.classList.add("hidden");cart=[];orderNo.textContent="Order #"+Date.now().toString().slice(-6);renderCart()};saveSettings.onclick=()=>{settings.name=storeName.value.trim()||"Cafe";settings.address=storeAddress.value.trim();settings.footer=receiptFooter.value.trim();saveSettings();renderSettings();toast("Pengaturan tersimpan.")};removeLogo.onclick=()=>{settings.logo="";saveSettings();renderSettings()};logoFile.onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>2e6)return toast("Logo maksimal 2MB.");const r=new FileReader();r.onload=()=>{settings.logo=r.result;saveSettings();renderSettings();toast("Logo berhasil dipasang.")};r.readAsDataURL(f)};
setInterval(()=>clock.textContent=new Date().toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}),1000);orderNo.textContent="Order #"+Date.now().toString().slice(-6);renderAll();