const products=[{id:1,name:"Kopi Susu Gula Aren",cat:"Coffee",price:22000,stock:42,emoji:"☕"},{id:2,name:"Americano",cat:"Coffee",price:18000,stock:35,emoji:"☕"},{id:3,name:"Cappuccino",cat:"Coffee",price:24000,stock:28,emoji:"☕"},{id:4,name:"Matcha Latte",cat:"Non-Coffee",price:26000,stock:21,emoji:"🍵"},{id:5,name:"Chocolate",cat:"Non-Coffee",price:24000,stock:19,emoji:"🍫"},{id:6,name:"Lychee Tea",cat:"Tea",price:18000,stock:31,emoji:"🧋"},{id:7,name:"French Fries",cat:"Food",price:20000,stock:16,emoji:"🍟"},{id:8,name:"Chicken Rice Bowl",cat:"Food",price:32000,stock:12,emoji:"🍚"},{id:9,name:"Croissant",cat:"Pastry",price:22000,stock:9,emoji:"🥐"}];let cart=[];let orders=JSON.parse(localStorage.getItem("cafe_orders")||"[]");let settings=JSON.parse(localStorage.getItem("cafe_settings")||"{}");let activeCat="All";
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function toast(s){const e=document.getElementById("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function renderCats(){const cats=["All",...new Set(products.map(p=>p.cat))];document.getElementById("categories").innerHTML=cats.map(c=>`<button class="${c===activeCat?"active":""}" onclick="setCat('${c}')">${c}</button>`).join("")}
function setCat(c){activeCat=c;renderCats();renderProducts()}
function renderProducts(){document.getElementById("products").innerHTML=products.filter(p=>activeCat==="All"||p.cat===activeCat).map(p=>`<button class="product" onclick="add(${p.id})"><span class="emoji">${p.emoji}</span><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="stock">Stok: ${p.stock}</div></button>`).join("")}
function add(id){const p=products.find(x=>x.id===id);const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({...p,qty:1});renderCart()}
function change(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);renderCart()}
function renderCart(){const el=document.getElementById("cartItems");el.innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><div><b>${x.name}</b><br><small>${money(x.price)} × ${x.qty}</small></div><div class="qty"><button onclick="change(${x.id},-1)">−</button><b>${x.qty}</b><button onclick="change(${x.id},1)">+</button></div></div>`).join(""):'<p style="padding:50px 0;text-align:center">Belum ada item.</p>';const sub=cart.reduce((s,x)=>s+x.price*x.qty,0),tax=sub*.1,total=sub+tax;document.getElementById("subtotal").textContent=money(sub);document.getElementById("discount").textContent=money(0);document.getElementById("tax").textContent=money(tax);document.getElementById("total").textContent=money(total)}
function checkout(){if(!cart.length)return toast("Tambahkan produk dulu.");const sub=cart.reduce((s,x)=>s+x.price*x.qty,0),tax=sub*.1,total=sub+tax;const order={id:"ORD-"+Date.now().toString().slice(-6),items:cart.map(x=>({name:x.name,qty:x.qty,price:x.price})),total,payment:document.getElementById("payment").value,note:document.getElementById("note").value,status:"Selesai",time:new Date().toLocaleString("id-ID")};orders.unshift(order);localStorage.setItem("cafe_orders",JSON.stringify(orders));cart=[];document.getElementById("note").value="";renderCart();renderOrders();renderReports();printReceipt(order);toast("Transaksi berhasil disimpan.")}
function printReceipt(o){const name=document.getElementById("storeName").value,address=document.getElementById("storeAddress").value,footer=document.getElementById("receiptFooter").value;const rows=o.items.map(i=>`<div>${i.name}<br>${i.qty} × ${money(i.price)} <span style="float:right">${money(i.qty*i.price)}</span></div>`).join("");const w=window.open("","_blank","width=380,height=650");if(!w)return;w.document.write(`<html><body style="font-family:monospace;width:300px;margin:20px auto;font-size:12px"><center><h2>${name}</h2><div>${address}</div></center><hr><div>No: ${o.id}<br>${o.time}<br>Bayar: ${o.payment}</div><hr>${rows}<hr><b style="font-size:16px">TOTAL <span style="float:right">${money(o.total)}</span></b><hr><center>${footer}</center><script>window.print();<\/script></body></html>`);w.document.close()}
function renderOrders(){document.getElementById("orderList").innerHTML=`<table><thead><tr><th>Order</th><th>Waktu</th><th>Item</th><th>Pembayaran</th><th>Total</th><th>Status</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${o.id}</b></td><td>${o.time}</td><td>${o.items.reduce((s,i)=>s+i.qty,0)} item</td><td>${o.payment}</td><td><b>${money(o.total)}</b></td><td><span class="status">${o.status}</span></td></tr>`).join("")||'<tr><td colspan="6">Belum ada pesanan.</td></tr>'}</tbody></table>`}
function renderInventory(){document.getElementById("inventoryList").innerHTML=`<table><thead><tr><th>Produk</th><th>Kategori</th><th>Stok</th><th>Status</th></tr></thead><tbody>${products.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.cat}</td><td>${p.stock}</td><td class="${p.stock<10?"low":""}">${p.stock<10?"Segera restock":"Aman"}</td></tr>`).join("")}</tbody></table>`}
function renderReports(){const revenue=orders.reduce((s,o)=>s+o.total,0),items=orders.reduce((s,o)=>s+o.items.reduce((a,i)=>a+i.qty,0),0),avg=orders.length?revenue/orders.length:0;const counts={};orders.forEach(o=>o.items.forEach(i=>counts[i.name]=(counts[i.name]||0)+i.qty));const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);document.getElementById("reportCards").innerHTML=[["Omzet",money(revenue)],["Transaksi",orders.length],["Item terjual",items],["Rata-rata order",money(avg)]].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");document.getElementById("topProducts").innerHTML="<h3>Produk Terlaris</h3>"+(top.map((x,i)=>`<p style="padding:9px 0;border-bottom:1px solid #eee">${i+1}. ${x[0]} <b style="float:right">${x[1]} terjual</b></p>`).join("")||"<p>Belum ada data.</p>")}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.view).classList.add("active")});
document.getElementById("clearCart").onclick=()=>{cart=[];renderCart()};document.getElementById("checkout").onclick=checkout;document.getElementById("saveSettings").onclick=()=>{settings={name:storeName.value,address:storeAddress.value,footer:receiptFooter.value};localStorage.setItem("cafe_settings",JSON.stringify(settings));toast("Pengaturan tersimpan.")};document.getElementById("restock").onclick=()=>toast("Modul stok masuk siap dihubungkan ke database.");
setInterval(()=>document.getElementById("clock").textContent=new Date().toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}),1000);
document.getElementById("orderNo").textContent="Order #"+Date.now().toString().slice(-6);renderCats();renderProducts();renderCart();renderOrders();renderInventory();renderReports();